### ISSUE TITLE
DBのbackupとactivateを任意の名前で出来る様にしたい

### ISSUE THREAD

**Issue by snowsunny** [PhantomCreation/wslave#14]
現状だとバックアップを取ると `wordpress.sql` と言う名前で固定だが、複数人で開発を行っている場合や、スナップショット的に保存したい場合に少し不便なので `backup` と `activate` を固定じゃなくて任意の名前で出来る様にしたい。 :pray:

**Comment by Kagetsuki** [comment]
実装するのに構造が結構複雑になってしまうのとメリットがあんまりない気がする。そう保管したい時はファイルをコピーしたり、別のgitブランチに保管したりすること。
